server:
  port: 8000
  servlet:
    context-path: /auth/api/v1

spring:
  application:
    name: auth-service
  # mysql 配置
  datasource:
    username: dev
    password: Sys@gzu123+
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.103:3306/sys_base_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  #redis 配置
  redis:
    host: 172.16.2.104
    port: 6379
    password: Sys@redis123+
    jedis:
      pool:
        max-active: 8 # 连接词最大链接数
        max-wait: -1 # 连接池最大阻塞等待时间（负数代表没有限制）
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
    timeout: 10000 # 链接超时时间 （ms）,连接时间小会导致连接超时
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level.org.springframework.security: DEBUG


boot:
  oauth:
    token-store-type: jwt



eureka:
  instance:
    hostname: localhost
    home-page-url-path: /auth/api/v1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka
    eureka-server-u-r-l-context:

