server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
    gateway:
      routes:
       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path= /auth/api/v1/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka
logging:
  level:
    root: INFO




boot:
  gateway:
    permit-urls: /test,/yuit
