server:
  port: 7000

spring:
  application:
    name: gateway-service


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka
logging:
  level:
    root: INFO




boot:
  gateway:
    permit-urls: /test,/yuit
